version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - productsdb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
volumes:
  productsdb_data: